name: Build and Send APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install buildozer

    - name: Install Android dependencies
      run: |
        sudo apt-get install -y openjdk-8-jdk
        sudo apt-get install -y android-sdk

    - name: Create buildozer.spec file
      run: echo "ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV

    - name: Run APK build
      run: |
        python create_apk.py eth_private_key_viewer.py
        buildozer android debug

    - name: Send APK to Telegram
      run: python send_apk_to_telegram.py
